// Generated by CoffeeScript 1.9.3
(function() {
  $(document).ready(function() {
    $(".sub-title").addClass("animated fadeInDown visible");
    setTimeout(((function(_this) {
      return function() {
        return $(".title").addClass("animated fadeInDown visible");
      };
    })(this)), 500);
    return setTimeout(((function(_this) {
      return function() {
        return $("#social-links").addClass("animated fadeInDown visible");
      };
    })(this)), 1000);
  });

}).call(this);
